name: pip_clients_attachments
version: "1.0.0"
description: Clients for Attachments microservice for Pip.Services in Dart
homepage: https://github.com/pip-services-content/pip-clients-attachments-dart

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  pip_services3_commons: ^1.0.9
  pip_services3_components: ^1.0.6
  pip_services3_rpc: ^1.0.3
  pip_services3_data: ^1.0.5
  pip_services_attachments: ^1.0.0
  http: "^0.12.0"
  angel_framework: ^2.1.1

dev_dependencies:
  test: '>=1.14.2 <2.0.0'
